branch-defaults:
  master:
    environment: null
environment-defaults:
  mediaff:
    branch: null
    repository: null
global:
  application_name: mediaff.com
  branch: null
  default_ec2_keyname: mediaff
  default_platform: PHP 7.0
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
