<?php

namespace AppBundle\Repository;

/**
 * CampaignInputDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignInputDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
