<?php

namespace AppBundle\Repository;

/**
 * cpcInputDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cpcInputDetailsRepository extends \Doctrine\ORM\EntityRepository
{

}
