<?php

namespace AppBundle\Repository;

/**
 * EmailTemplateDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
