<?php

namespace AppBundle\Repository;

/**
 * newAdOfferDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newAdOfferDetailsRepository extends \Doctrine\ORM\EntityRepository
{
    public function offerDetailsTable() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            -> select('adof.url as OfferURL,
                              adof.offerName as OfferName,
                              adof.geo as OfferGeo,
                              pt.partner_name as OfferPartner,
                              st.statusName as OfferStatus')
            -> from('AppBundle:newAdOfferDetails', 'adof')
            -> join('adof.partner', 'pt')
            -> join('adof.offerStatus', 'st')
        ;
        $result = $qb ->getQuery() ->getResult();
        return $result;
    }//concolidated pull function for campaigns dash
}
