<?php

namespace AppBundle\Repository;

/**
 * OfferDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
