<?php

namespace AppBundle\Repository;

/**
 * PartnerTypeDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerTypeDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
