<?php

namespace AppBundle\Repository;

/**
 * RefADKCategoryDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefADKCategoryDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
