<?php

namespace AppBundle\Repository;

/**
 * RefOfferStatusDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefOfferStatusDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
