<?php

namespace AppBundle\Repository;

/**
 * RefTireDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTireDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
