<?php

namespace AppBundle\Repository;

/**
 * RefWebTrafficTypeDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefWebTrafficTypeDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
