<?php

namespace AppBundle\Repository;

/**
 * SendyAppsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendyAppsRepository extends \Doctrine\ORM\EntityRepository
{
}
