<?php

namespace AppBundle\Repository;

/**
 * StatsMonthlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsMonthlyRepository extends \Doctrine\ORM\EntityRepository
{
}
