<?php

namespace AppBundle\Repository;

/**
 * StatsYearlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsYearlyRepository extends \Doctrine\ORM\EntityRepository
{
}
