<?php

namespace AppBundle\Repository;

/**
 * StatsWeeklyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsWeeklyRepository extends \Doctrine\ORM\EntityRepository
{
}
