<?php

namespace AppBundle\Repository;

/**
 * SubscriberAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
