<?php

namespace AppBundle\Repository;

/**
 * SubscriberADKCampErrorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberADKCampErrorsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMaxRow() {
        return $this->getEntityManager()
            ->createQuery('SELECT max(s.id) FROM AppBundle:SubscriberADKCampErrors s')
            ->getSingleScalarResult();
    }
}
